site_name: Documentação do Meu Projeto

theme:
  name: material

  palette:
    - scheme: default
      primary: blue
      accent: orange 

  nav:
  - Início: index.md
  - Sobre: sobre.md

  plugins:
  - search
  - git-revision-date-localized