site_name: Documentação do Meu Projeto

theme:
  name: material

  palette:
    - scheme: default
      primary: blue
      accent: orange 

  nav:
  - Início: index.md
  - Sobre: sobre.md
  - Instruções: instrucoes.md
  plugins:
  - search
  - git-revision-date-localized

  extra:
  version:
    provider: mike